DROP DATABASE IF EXISTS user_db;
CREATE DATABASE user_db;

USER user_db;

CREATE TABLE user (
id int NOT NULL AUTO_INCREMENT,
user_name VARCHAR (100) NOT NULL,
password VARCHAR (100) NOT NULL,
createdAt TIMESTAMP NOT NULL,
PRIMARY KEY (id)
);
